name: Release on GitHub & PyPI

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: "${{ matrix.build }} ${{ matrix.os }} ${{ matrix.arch }}"
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        arch: ["x86_64"]
        build:
          [
            "cp39-manylinux_x86_64",
            "cp310-manylinux_x86_64",
            "cp311-manylinux_x86_64",
          ]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "true"
      - name: Install build dependencies
        run: python3 -m pip install cibuildwheel
      - run: cibuildwheel --output-dir wh
        env:
          CIBW_BUILD: ${{ matrix.build }}
          CIBW_ARCHS: ${{ matrix.arch }}
          CIBW_MANYLINUX_X86_64_IMAGE: "dockcross/manylinux_2_28-x64"
          CIBW_REPAIR_WHEEL_COMMAND: ""
      - uses: actions/upload-artifact@v3
        with:
          path: wh

  release:
    needs: ["build"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
      - run: python -m pip install twine
      - run: twine upload -u __token__ -p "${{ secrets.PYPI_TOKEN }}" artifact/cmeel_casadi_kin_dyn*.whl
      - run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - run: gh release create -t "Release ${{ env.TAG}}" -n "$(awk '/## \[${{ env.TAG }}] - /{flag=1;next}/## \[/{flag=0}flag' CHANGELOG.md)" ${{ env.TAG }} artifact/cmeel_casadi_kin_dyn*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
